### PR TITLE
Remove eval (Function) from specials

### PR DESCRIPTION
**Pull request by lann**

### CODE REVIEW

**Comment by skeggse** [comment]
Why?

**Comment by lann** [comment]
Eval triggers warnings in many execution environments, and is outright forbidden in others (packaged chrome apps).

**Comment by skeggse** [comment]
Not targetting anything besides Node. Thanks, though.

**Comment by Marsup** [comment]
Although his solution is wrong in that it changes the behavior, it can be converted to static code, why isn't it that way ?

**Comment by arb** [comment]
Agreed. This should be reopened.

**Comment by lann** [comment]
CI failure is due to lint in an unmodified file:
```
Linting results:
	/home/travis/build/hapijs/isemail/test/index.js:
		Line 164: one-var - Split 'const' declarations into multiple statements.
```

**Comment by hueniverse** [comment]
@lann might as well fix that.

**Comment by jeffbski** [comment]
Can this be merged now?

It seems like a good change.

**Comment by skeggse** [comment]
Would you please squash your commits, @lann?

**Comment by skeggse** [comment]
TIL there's a built-in squash button.

**Comment by hueniverse** [comment]
@skeggse Make sure to assign yourself and set a milestone and labels.

**Comment by ChrisMcKee** [comment]
any idea when 2.2.0 will be going out?

**Comment by skeggse** [comment]
@ChrisMcKee Done. Thanks for reminding me :)

**Comment by ChrisMcKee** [comment]
Thanks @skeggse  :smiley:

**Pull request merged**
