### PR TITLE
Add changelog.md

### PR DESCRIPTION
**Pull request by Nargonath**

### CODE REVIEW

**Comment by skeggse** [comment]
Thanks for adding! I don't currently follow this approach. I'm open to doing so, but maybe we should update the changelog to reflect that?

**Comment by Nargonath** [comment]
@skeggse Yeah sorry, I assumed it was an org approach and that every project was already following it. Indeed we can modify the changelog to better suit your actual process. What would you like to change?

I was waiting for the lead maintainer to merge it himself in the first PRs I did but then I figured I'll just save everyone's time. My bad.

**Comment by skeggse** [comment]
Is the actual approach (detailed from the perspective of a maintainer) documented anywhere? It seems like a neat approach, and I'd like to understand and possibly apply it here.

**Comment by Nargonath** [comment]
If it is, I'm not aware of it. It all started from an informal conversation on Slack. Here is the conversation:
image

Anyway that could be a good addition to our docs but I don't really know where this kind of documentation is supposed to be.

**Comment by skeggse** [comment]
TIL we had a slack :joy:

**Comment by Nargonath** [comment]
Yeah I thought of removing them from hapijs.com. Last time I checked latest message dated from 1 or 2 years ago.

**Pull request merged**
