### PR TITLE
Update error level examples in README

### LINKED ISSUE #174: The library validates everything correctly
I am using node v8.10.0. This is my first time using this library so I don't know if it's working on older node versions, but when I'm running the examples, everything validates correctly: 

```js
$ node
> var Isemail = require('isemail');
undefined
> Isemail.validate('test@iana.org');
true
> Isemail.validate('test@iana.org', {errorLevel: true});
0
> Isemail.validate('test@e.com', {errorLevel: true});
0
> Isemail.validate('test@e.com', {errorLevel: 7});
0
> Isemail.validate('test@e.com', {errorLevel: 6});
0
```

I also did more tests, and basically everything that has a "@" validates, even without domain names.

### PR DESCRIPTION
**Pull request by WesTyler**
Closes #174

### CODE REVIEW

**Comment by WesTyler** [comment]
(Looks like `lab` is taking exception with Node v10.x's BigInt stuff)

**Comment by skeggse** [comment]
Can we also add an example that includes a weird special character in the domain part? The code (`10`) you're getting is actually just a warning.

**Comment by WesTyler** [comment]
These were the other ones I was considering using instead of the warn-level one. These okay?
```
> Isemail.validate('test@iana&12');
false
> Isemail.validate('test@iana&12', {errorLevel: true});
65
> Isemail.validate('test@', {errorLevel: true});
131
```

**Comment by skeggse** [comment]
Perfect, thanks!

**Comment by skeggse** [comment]
Per https://github.com/hapijs/lab/pull/837, we should just be able to update lab! I can do in a little bit, or you can throw up another PR. Either way.

**Pull request merged**
