### PR TITLE
TLD Check described in #170

### PR DESCRIPTION
**Pull request by VeeeneX**
Added simple `tldAtom.toLowerCase()` to check against lowercase list of tlds

### CODE REVIEW

**Comment by skeggse** [comment]
At first glance, this looks great, thanks!

It [looks like](http://unicode.org/faq/idn.html#11) IDN names might be included in this consideration, and it seems like the case-insensitive check should handle those as well? Currently, `toLowerCase` does handle unicode characters, but I want to be sure that it handles the correct set to avoid the possibility of accepting an email address as valid when it shouldn't be.

**Comment by VeeeneX** [comment]
I think so, those IDN should be handled. And for the second part that will require some testing...

**Comment by skeggse** [comment]
My primary concern is that I want to ensure that ecmascript's lowercasing process modifies characters in the exact same manner as required by IDNs.

**Comment by skeggse** [comment]
To address my concerns above, I've opened a PR that would obsolete this one: hapijs/isemail#178.

**Comment by skeggse** [comment]
Closing in favor of #178.

**Pull request closed without merging**
