### PR TITLE
chore: add TS type declaration and pkg.json types entry

### PR DESCRIPTION
**Pull request by alexsasharegan**
Convenience for TypeScript and vscode users.

image
image

### CODE REVIEW

**Comment by skeggse** [comment]
Ah, thanks! I'm just now noticing that we didn't deprecate the callback function like we were going to - there isn't any async behavior anymore.

**Comment by alexsasharegan** [comment]
Let me know if you want it documented differently, or if you update the API and would rather have me update the typings.

**Comment by skeggse** [comment]
I'm not familiar with typescript, but is there any reason to not follow hapijs' style guidelines in regards to semicolon usage and indentation?

**Comment by alexsasharegan** [comment]
I didn't catch that, sorry! I'll see about getting my formatter to cooperate.

**Comment by skeggse** [comment]
>Let me know if you want it documented differently, or if you update the API and would rather have me update the typings.

I'll update the API and docs - can you update the ts definition to remove the optional callback? (I'm not at my computer right now but will be shortly)

**Comment by alexsasharegan** [comment]
I just scanned the style guide briefly. Basically just switched to using spaces and semis. Also removed the callback param.

**Comment by skeggse** [comment]
Joi appears to be the only project that [includes](https://github.com/hapijs/joi/blob/master/.editorconfig) a .editorconfig. We use [lab](https://github.com/hapijs/lab) to validate adherence to our [style guide](https://hapijs.com/styleguide). See also https://github.com/hapijs/contrib/issues/38.

**Comment by skeggse** [comment]
Merged, thanks!

**Comment by alexsasharegan** [comment]
Awesome! Do you have a set release cycle? When might this make it onto npm so I can remove my own typings?

**Comment by skeggse** [comment]
I'll go update the docs when I'm at my computer and release that together as `3.1.1`.

**Comment by alexsasharegan** [comment]
Cheers! Thank you!

**Comment by Marsup** [comment]
@skeggse It's not going to be enough, .npmignore will drop it on publish.

**Comment by alexsasharegan** [comment]
Doesn't `.npmignore` whitelist `lib/*`?

**Comment by skeggse** [comment]
Released in `3.1.1` (`callback` is just deprecated until `4.0.0`). The `npmignore` does correctly whitelist `lib/`, though we could move that definition into the `files` array of the `package.json` instead.

**Comment by alexsasharegan** [comment]
True! I just followed what you guys had going. Didn't even realize I saved myself that faux pas!

**Pull request merged**
